[package]
name = "gnuradio"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
name = "gnuradio_config_info"
path = "gnuradio-runtime/apps/gnuradio-config-info.rs"
crate-type = ["staticlib"]
